### ISSUE TITLE
BUG: pluralisation of field name is too naive

### ISSUE THREAD

**Issue by dimaip** [Globobeet/keystone-sortable-list-plugin#1]
I have a `story` field. To get all stories you need to query `allStories`, but the plugin tries to query `allStorys` and thus doesn't work.

**Comment by joshlasdin** [comment]
@dimaip Thanks, will definitely look into this and see if there's a way that other Keystone modules handle plural-fication

**Comment by joshlasdin** [comment]
@dimaip Just published `0.1.2`, which should resolve this issue. Please let me know if you're still having trouble with it. Thanks!

**Comment by dimaip** [comment]
You rock, thank you!
